version: '3'

services:
  app:
    build: .
    container_name: python_app
    ports:
      - "8050:8050"
    env_file: .env
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    networks:
      - backend

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: radmap
    environment:
      MONGO_INITDB_ROOT_USERNAME: root      # YOUR MONGODB USER
      MONGO_INITDB_ROOT_PASSWORD: password  # YOUR MONGODB PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
