version: '3'

services:
  app:
    build: .
    container_name: python_app
    ports:
      - "8050:8050"
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - .:/usr/src/app
    networks:
      - backend

  mariadb:
    image: mariadb:latest
    container_name: radmap_db
    environment:
      MYSQL_ROOT_PASSWORD: password       # Your MariaDB root password
      MYSQL_DATABASE: radmap              # Optional: Pre-create database
      MYSQL_USER: root                    # Optional: Create user
      MYSQL_PASSWORD: password            # Optional: Set user password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend:
